### ISSUE TITLE
mydomain.INET6_ATON does not exist

### ISSUE THREAD

**Issue by mmokrejs** [Pierre-Lannoy/wp-ip-locator#1]
Hi Pierre,
  I just installed the plugin v3.5.1 and created a file logger instance using DecaLog https://wordpress.org/plugins/decalog/ . One of the entries shows the SQL table is either missing a column or a function is not defined. I am not sure how to interpret it.

```
AJAX.CRITICAL: A database error was detected during the page rendering: “FUNCTION mydomain.INET6_ATON does not exist“ in the query “SELECT `country` FROM `wp_iplocator_v4` WHERE `from` ≤ INET6_ATON(`195.201.152.254`) AND `to` ≥ INET6_ATON(`195.201.152.254`) ;“. {"class":"db","component":"MySQL compatible","version":"5.5" ...
```

**Environment (please complete the following information):**
 - PHP version: 7.3.24-3+ubuntu
 - WordPress version and flavour: 5.9
 - mysql version: 5.5.15

**Comment by Pierre-Lannoy** [comment]
Hello @mmokrejs !
This is due to the fact that `INET6_ATON` function is available from MySQL 5.6 (and not before). Your version is too old to support IP Locator and, btw, doesn't meets [WordPress requirements](https://wordpress.org/about/requirements/).
Sorry.

**Comment by mmokrejs** [comment]
Thank you, @Pierre-Lannoy , but could is it really critical error? Anyway, I wouldn't have IPv6 enabled. So could IP Locator work even without this support in mysql? And could it report in the WP menu whether requisite criteria are met?

**Comment by Pierre-Lannoy** [comment]
I know the name of this function is a bit confusing, but it processes IPv4 and IPv6 adresses. So IP Locator is fully unusable.

I'm really sorry for that. I know it's a little harsh to hear, but I stick to WP requirements, and never test these requirements are covered… I consider every WP admin meets these requirements when installing WP and don't take security / perf risks with outdated versions.

Hope it helps you to understand the situation.

**Comment by mmokrejs** [comment]
Well, today admin of the container did the upgrade of mysql so it should be no problem for me but nevertheless it could report the unmet specs to the WP admin. It is uncommon someone like me installed WP-syslogging tool and grepped for error in the zillions of lines. Well, it was my 2c. Thank you anyway for your quick answers.
