### ISSUE TITLE
Synchronisation des tables WooCommerce et Stockage des Logs de Action Scheduler dans les commentaires

### ISSUE THREAD

**Issue by Mil1** [Pierre-Lannoy/wp-ip-locator#4]
**Describe the bug**
Sur un WordPress avec WooCommerce, j'ai mis du temps à trouver mais je me suis rendu compte qu l'extension IP Locator rends impossible la synchronisation des commandes de l'ancien système au nouveau HPOS de WooCommerce.

Il y a un autre problème : le stockage des logs des actions dans les commentaires. C'est cela qui m'a permis de remonté le problème du dessus dont je n'arrivais pas à trouver la source.

**To Reproduce**
1. Création d'une installation neuve
2. Ajout de WooCommerce
3. Ajout d'IP Locator
4. Bug n°1 : Voir les commentaires
5. Création d'une commande (meme sans produit ça marche)
6. Forcer la synchronisation vers l'ancien système (Réglages -> Avancée -> Fonctionnalités)
7. Retournée dans les commentaires voir cette erreur :
_Une défaillance est survenue lors de la récupération de cette action : L’action [468989] comporte des arguments non valides. Elle ne peut pas être un JSON décodé dans un tableau. $args = array (
)_ en lien avec l'action wc_run_batch_process

et en supprimant cette ligne, cela règle le problème, il me semble. 
ip-locator.php 41 : add_filter( 'action_scheduler_migration_dependencies_met', '__return_false' ); 

Qui bloque apparemment la migration de l’utilisation des nouvelles tables pour gérer les actions. Solution pour les versions avant 3.0 de Action Scheduler : https://actionscheduler.org/version3-0/

_I would like to update a plugin for testing that includes Action Scheduler 3.0 but would like to postpone the migration until that testing is complete. Is that possible?

Yes, while we recommend migrating to custom tables as soon as possible for performance reasons, you can use add_filter( 'action_scheduler_migration_dependencies_met', '__return_false' ); to prevent the migration from initiating._

Merci Pierre.

**Comment by Pierre-Lannoy** [comment]
Hello !
Merci de ce rapport d'erreur. Le principal problème  (migration des tables) sera réglé dans la prochaine version (d'ici quelques semaines).
En revanche, pour le second sujet (le stockage des logs des actions dans les commentaires), ce n'est pas IP Locator qui fait cela mais bien Action Scheduler. Oui, c'est crado mais ils ont toujours fait comme ça… :/

**Comment by Pierre-Lannoy** [comment]
Bon, en fait j'ai eu le temps de corriger et publier la mise à jour (3.10.1) 😄

**Comment by Mil1** [comment]
Ça c'est de la réactivité ! top ! Merci

**Comment by Mil1** [comment]
Ça c'est de la réactivité ! top ! Merci
